-- 코드를 입력하세요
SELECT A.REST_ID AS REST_ID, A.REST_NAME AS REST_NAME,
    A.FOOD_TYPE AS FOOD_TYPE, A.FAVORITES AS FAVORITIES,
    A.ADDRESS AS ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A INNER JOIN REST_REVIEW B
ON A.REST_ID=B.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITIES DESC;