-- 코드를 작성해주세요
WITH RECURSIVE MET AS
(
    SELECT ID, PARENT_ID, 1 AS LEVEL
        FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, B.LEVEL+1 AS LEVEL
        FROM ECOLI_DATA A
            JOIN MET B ON A.PARENT_ID=B.ID
)

SELECT COUNT(*) AS COUNT, LEVEL AS GENERATION
    FROM MET
WHERE NOT EXISTS(SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID=MET.ID)
GROUP BY LEVEL
ORDER BY LEVEL